---

#- name: Create ssh directory
#  shell: mkdir -p /storage/docker/images/.ssh
#  ignore_errors: yes

- file:
    path: /storage/docker/images/.ssh
    owner: '{{ USER }}'
    group: '{{ USER }}'
    state: directory
    mode: 0700
  ignore_errors: yes

- name: Generate ssh-keys for dev user
  user:
    name: '{{ USER }}'
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: /storage/docker/images/.ssh/id_rsa
  ignore_errors: yes

- name: Assign Permissions to ssh directory
  shell: chown -R {{ USER }}. /storage/docker/images/.ssh/
  ignore_errors: yes

- name: Assign Permissions to ssh directory
  shell: chmod -R 700 /storage/docker/images/.ssh/
  ignore_errors: yes

- name: Echo public key to authorized_keys file
  shell: /storage/docker/images/.ssh/id_rsa.pub > /storage/docker/images/.ssh/authorized_keys
  ignore_errors: yes

- name: Get id_rsa.pub key as an output
  shell: cat /storage/docker/images/.ssh/id_rsa.pub
  register: pubkey
  ignore_errors: yes
